mra_atlas: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v0/subject_ids.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v0/ixi_metadata.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ['Background', 'Vessel','CSF', 'cGM', 'WM', 'BG', 'Ventricles', 'Cerebellum', 'Deep_GM', 'Brainstem', 'HippocampiAmygdala']
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # class_weights: [0.00, 2.0, 3.0, 2.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

feta_atlas: # dhcp neonates multimodal dataset config
  dataset_name: feta_atlas
  subject_ids: /home/zhangx/CINeMA/vessel_data/Feta_data/subject_ids.yaml
  tsv_file: /home/zhangx/CINeMA/vessel_data/Feta_data/feta_metadata.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: false   # 将年龄作为图谱生成的“时间轴”条件
    sex: false       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 18 # min value to sample 
      max: 100 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ['Background', 'CSF', 'GM', 'WM', 'Ventricles', 'Cerebellum', 'Deep_GM', 'Brainstem']
  class_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [155, 155, 155] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_iop: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_iop
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v0/subject_ids_IOP.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v0/ixi_metadata.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ['Background', 'Vessel','CSF', 'cGM', 'WM', 'BG', 'Ventricles', 'Cerebellum', 'Deep_GM', 'Brainstem', 'HippocampiAmygdala']
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # class_weights: [0.00, 2.0, 3.0, 2.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_non_iop: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_non_iop
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v0/subject_ids_non_IOP.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v0/ixi_metadata.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ['Background', 'Vessel','CSF', 'cGM', 'WM', 'BG', 'Ventricles', 'Cerebellum', 'Deep_GM', 'Brainstem', 'HippocampiAmygdala']
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # class_weights: [0.00, 2.0, 3.0, 2.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_synthseg_label12: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_synthseg_label12
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v1/subject_ids_label12.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v1/ixi_metadata_label12.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ["Background", "Vessel","left_cerebral_white_matter", "left_cerebral_cortex", "csf_ventricles", "left_cerebellum", "left_deep_gray_nuclei","brainstem", "right_cerebral_white_matter", "right_cerebral_cortex", "right_cerebellum", "right_deep_gray_nuclei"]
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # class_weights: [0.00, 2.0, 3.0, 2.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_synthseg_label16: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_synthseg_label16
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v1/subject_ids_label16.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v1/ixi_metadata_label16.tsv
  modalities: ['MRA', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names:  ["Background", "Vessel", "left_cerebral_white_matter", "left_cerebral_cortex", "left_ventricular_csf", "left_cerebellum", "left_deep_gray_nuclei", "left_limbic_medial_temporal", "midline_csf_ventricles", "brainstem", "right_cerebral_white_matter", "right_cerebral_cortex", "right_ventricular_csf", "right_cerebellum", "right_deep_gray_nuclei", "right_limbic_medial_temporal"]
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_synthseg_label_t1: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_synthseg_label_t1
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v1/subject_ids_label_t1.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v1/ixi_metadata_label_t1.tsv
  modalities: ['MRA', 'T1', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names:  ["Background", "Vessel", "left_cerebral_white_matter", "left_cerebral_cortex", "left_ventricular_csf", "left_cerebellum", "left_deep_gray_nuclei", "left_limbic_medial_temporal", "midline_csf_ventricles", "brainstem", "right_cerebral_white_matter", "right_cerebral_cortex", "right_ventricular_csf", "right_cerebellum", "right_deep_gray_nuclei", "right_limbic_medial_temporal"]
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'

mra_atlas_synthseg_label_t1_fast: # dhcp neonates multimodal dataset config
  dataset_name: mra_atlas_synthseg_label_t1_fast
  subject_ids: /leonardo/home/userexternal/xzhang01/data/v1/subject_ids_label_t1_fast.yaml
  tsv_file: /leonardo/home/userexternal/xzhang01/data/v1/ixi_metadata_label_t1_fast.tsv
  modalities: ['MRA', 'T1', 'Seg'] # modality names in the tsv file 
  conditions:  # conditions with number of dimensions possibly used for atlas conditioning
    scan_age: true   # 将年龄作为图谱生成的“时间轴”条件
    sex: true       # 如果您想生成“男性/女性特定图谱”，改为 true
    birth_age: false # 成人数据不需要这个，设为 false
  constraints:  # sample only subjects that meet all constraints
    scan_age: 
      type: numeric # numeric, categoric, or binary
      min: 19 # min value to sample 
      max: 87 # max value to sample
      distribution: # distribution of the values to sample, if dropped we sample randomly from the range
        type: 'uniform_fillup' # so far only uniform fillup is supported 
        priority: 10 # higher priority means more important
    sex:
      type: categoric
      values: ['M', 'F']

  label_names: ['Background', 'Vessel','CSF', 'cGM', 'WM', 'BG', 'Ventricles', 'Cerebellum', 'Deep_GM', 'Brainstem', 'HippocampiAmygdala']
  class_weights: [0.1, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  world_bbox: [240, 240, 120] # size of the (roughly) smallest COMMON bounding box for all subjects in mm
  normalize_values: 'minmax' # 'minmax' or 'zscore'